dj4e-samples/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    # Sample applications
    path('hello/', include('hello.urls')),
    path('users/', include('users.urls')),
    path('tracks/', include('tracks.urls')),
    path('views/', include('views.urls')),
    path('route/', include('route.urls', namespace='nsroute')),
    path('tmpl/', include('tmpl.urls')),
    path('gview/', include('gview.urls')),
    path('session/', include('session.urls')),
    path('authz/', include('authz.urls')),
    path('getpost/', include('getpost.urls')),
    path('form/', include('form.urls')),
    path('crispy/', include('crispy.urls')),
    path('myarts/', include('myarts.urls')),
    path('menu/', include('menu.urls')),
    path('forums/', include('forums.urls')),
    path('pics/', include('pics.urls')),
    path('favs/', include('favs.urls')),
    path('favwc/', include('favwc.urls')),
    path('favsql/', include('favsql.urls')),
    path('rest/', include('rest.urls')),
    path('autos/', include('autos.urls')),
    path('usermodel/', include('usermodel.urls')),
    path('fetch/', include('fetch.urls')),
    path('chat/', include('chat.urls')),
    path('util/', include('util.urls')),
    path('well/', include('well.urls')),
    path('tagme/', include('tagme.urls')),
    path('zip/', include('zip.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

favwc/urls.py
from django.urls import path, reverse_lazy
from . import views

# In urls.py reverse_lazy('favwc:all')
# In views.py class initialization reverse_lazy('favwc:all')
# In views.py methods reverse('favwc:all')
# In templates {% url 'favwc:thing_update' thing.id %}

app_name='favwc'
urlpatterns = [
    path('', views.ThingListView.as_view(), name='all'),
    path('thing/<int:pk>', views.ThingDetailView.as_view(), name='thing_detail'),
    path('thing/create',
        views.ThingCreateView.as_view(success_url=reverse_lazy('favwc:all')), name='thing_create'),
    path('thing/<int:pk>/update',
        views.ThingUpdateView.as_view(success_url=reverse_lazy('favwc:all')), name='thing_update'),
    path('thing/<int:pk>/delete',
        views.ThingDeleteView.as_view(success_url=reverse_lazy('favwc:all')), name='thing_delete'),
    path('thing/<int:pk>/toggle',
        views.ToggleFavoriteView.as_view(), name='thing_toggle'),
]

polls/polls/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
]

zip/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name='zip'
urlpatterns = [
    path('', TemplateView.as_view(template_name='zip/main.html'), name='main'),
    path('upload', views.UploadView.as_view(), name='upload'),
]

favwc/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings

class Thing(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
            related_name='favwc_thing_owner')
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Fav', related_name='favwc_favorite_things')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        return self.title

class Fav(models.Model) :

    thing = models.ForeignKey(Thing, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='favwc_users')

    # https://docs.djangoproject.com/en/4.2/ref/models/options/#unique-together
    class Meta:
        unique_together = ('thing', 'user')

    def __str__(self) :
        return '%s likes %s'%(self.user.username, self.thing.title[:10])

favwc/views.py
from .models import Thing, Fav

from django.views import View
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from django.contrib.auth.mixins import LoginRequiredMixin

from myarts.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView

class ThingListView(OwnerListView):
    model = Thing
    template_name = "favwc/list.html"

    def get(self, request) :
        thing_list = Thing.objects.all()
        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favwc_favorite_things.values('id')
            print(rows)
            # favorites = [2, 4, ...] using list comprehension
            favorites = [ row['id'] for row in rows ]
        print(favorites)
        ctx = {'thing_list' : thing_list, 'favorites': favorites}
        return render(request, self.template_name, ctx)

class ThingDetailView(OwnerDetailView):
    model = Thing
    template_name = "favwc/detail.html"

class ThingCreateView(OwnerCreateView):
    model = Thing
    fields = ['title', 'text']
    template_name = "favwc/form.html"

class ThingUpdateView(OwnerUpdateView):
    model = Thing
    fields = ['title', 'text']
    template_name = "favwc/form.html"

class ThingDeleteView(OwnerDeleteView):
    model = Thing
    template_name = "favwc/delete.html"

# csrf exemption in class based views
# https://stackoverflow.com/questions/16458166/how-to-disable-djangos-csrf-validation
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError

@method_decorator(csrf_exempt, name='dispatch')
class ToggleFavoriteView(LoginRequiredMixin, View):
    # Add get for manual retrieval
    def get(self, request, pk) :
        t = get_object_or_404(Thing, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, thing=t).delete()
            return HttpResponse("Favorite present: "+str(fav))
        except:
            return HttpResponse("Favorite not present: "+str(t)+" -> "+str(request.user))

    def post(self, request, pk) :
        t = get_object_or_404(Thing, id=pk)
        fav = Fav(user=request.user, thing=t)
        try:
            fav.save()
            return HttpResponse("Favorite added 42")
        except IntegrityError:  # Already there, lets delete...
            Fav.objects.get(user=request.user, thing=t).delete()
            return HttpResponse("Favorite deleted 42")
        return HttpResponse("Something went wrong")

favwc/templates/favwc/delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Thing</h1>

<p>Are you sure you want to delete the thing: {{ thing }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" value="Cancel" onclick="window.location.href='{% url 'favwc:all' %}';return false;">
</form>
{% endblock %}

favwc/templates/favwc/detail.html
{% extends "base_bootstrap.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/4.2/ref/contrib/humanize -->
{% block content %}
<span style="float: right;">
({{ thing.updated_at|naturaltime }})
{% if thing.owner == user %}
<a href="{% url 'favwc:thing_update' thing.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'favwc:thing_delete' thing.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ thing.title }}</h1>
<p>
{{ thing.text }}
</p>
<p>
</p>
<p>
<a href="{% url 'favwc:all' %}">All things</a>
</p>
{% endblock %}

favwc/templates/favwc/form.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'favwc:all' %}';return false;">
  </form>
</p>
{% endblock %}

favwc/templates/favwc/list.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Favorite Things (WC)</h1>
<p>
{% if thing_list %}
<ul>
  {% for thing in thing_list %}
    <li>
        <a href="{% url 'favwc:thing_detail'  thing.id %}">{{ thing.title }}</a>
        {% if thing.owner_id == user.id %}
        (<a href="{% url 'favwc:thing_update' thing.id %}">Edit</a> |
        <a href="{% url 'favwc:thing_delete' thing.id %}">Delete</a>)
        {% endif %}
        {% if user.is_authenticated %}
        <dj4e-favstar 
            onclick="favToggle(this, '{% url 'favwc:thing_toggle' thing.id %}');"
            {% if thing.id in favorites %} fav {% endif %} 
        >
        </dj4e-favstar>
        {% endif %}
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no things in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'favwc:thing_create' %}">Add a Thing</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'favwc:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'favwc:all' %}">Login</a>
{% endif %}
</p>
<script>
function favToggle(element, url) {
    console.log('POSTing to', url);
    fetch(url, { method: 'POST', body: '{}' } )
    .then((response) => {
        console.log(url, 'success');
        element.toggleAttribute('fav');
    }).catch((error) => {
        alert('Url failed with '+error+' '+url);
    });
}
</script>
<script type="module" src="/site/wc/dj4e-favstar.js"></script>
{% endblock %}